version: '2.1'
services:
  postgres:
    # container_name: postgres
    # hostname: postgres
    # restart: always
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../../database/biodevs.sql:/docker-entrypoint-initdb.d/biodevs.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    # container_name: pgadmin
    # hostname: pgadmin
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      SCRIPT_NAME: ${SCRIPT_NAME}
    volumes:
       - pgadmin:/var/lib/pgadmin

  app:
    # restart: always
    # https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentication-problem
    platform: linux/amd64
    build: ../../api
    volumes: 
      - logs:/Bio-Dev/metabolomics/logs
      - plots:/Bio-Dev/metabolomics/static/plots
      - uploads:/Bio-Dev/metabolomics/uploads
    depends_on:
      - postgres

  nginx:
    # restart: unless-stopped
    # container_name: nginx
    build: 
      context: ../../client
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./certbot:/var/www/certbot
      - ./ssl:/app/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - pgadmin
      - app

volumes:
  # To Persist the PostGre Database
  postgres-data:
  # To Persist the Created Plot Diagrams
  plots:
  # To Persist the logs
  logs:
  # To Persist the PostGre Database Connections
  pgadmin:
  # The Place where the backend uploads files
  uploads:
