export const FILE_DETAILS_MAP = {
  id: 'Scan Id',
  // compound_name: 'Compound',
  data_source_name: 'Data Source',
  // file_format: 'File format',
  file_name: 'File Name',
  import_date: 'Import date',
  mass_spectype_name: 'Mass Spec type',
  predicted_experimental: 'Pred or Expr',
  method: "Method"
  // spectrum_id: 'Spectrum Id',
};

export const SCAN_DETAILS_MAP = {
  spec_scan_num: 'Scan Number',
  ms_level: 'MS Level',
  retention_time_secs: 'Retention Time',
  centroided: 'Centroided',
  polarity: 'Polarity',
  prec_scan_num: 'Pre scan number',
  precursor_mass: 'Precursor Mass',
  precursor_intensity: 'Precursor Intensity',
  precursor_charge: 'Precursor Charge',
  collision_energy: 'Collision Energy',
  original_peaks_count: 'Orig. Peaks Count',
  total_ion_current: 'Total Ion Current',
  base_peak_mz: 'Base Peak mz',
  base_peak_intensity: 'Base Peak Intensity',
  ionisation_energy: 'Ionisation Energy',
  low_mz: 'Low mz',
  high_mz: 'High mz',
  injection_time_secs: 'Injection Time',
  peak_index: 'Peak Index',
  peak_id: 'Peak Id',
  scan_index: 'Scan Index',
  spectrum_id: 'Spectrum Id',
};
