export enum RECORD_NAME_API_ENUM {
  TOTAL_COMPOUNDS = 'ALL_COMPOUNDS',
  MISSING_INCHIKEY = 'MISSING_INCHIKEY',
  MISSING_SMILES = 'MISSING_SMILES',
  MISSING_MS2 = 'MISSING_MS2',
  MISSING_CHEBIEY = 'MISSING_CHEBIEY',
  MISSING_URL = 'MISSING_URL',
}
